// Generated by Java* Fuzzer test generator (1.0.001). Mon Apr 10 13:04:59 2023
public class Test {

    public static final int N = 400;

    public static long instanceCount=-318851180L;
    public static double dFld=0.1260;
    public static int iFld=-12;
    public static float fFld=-1.203F;
    public static int iArrFld[]=new int[N];
    public static volatile long lArrFld[]=new long[N];

    static {
        FuzzerUtils.init(Test.iArrFld, 14);
        FuzzerUtils.init(Test.lArrFld, 2156182139L);
    }

    public static long iMeth_check_sum = 0;
    public static long vMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;

    public static void vMeth1(int i6) {

        float f=0.390F;
        int iArr[]=new int[N];

        FuzzerUtils.init(iArr, 50650);

        iArr[(i6 >>> 1) % N] += i6;
        i6 = i6;
        iArr = FuzzerUtils.int1array(N, (int)-24295);
        iArr = FuzzerUtils.int1array(N, (int)-55535);
        i6 >>>= i6;
        f += i6;
        vMeth1_check_sum += i6 + Float.floatToIntBits(f) + FuzzerUtils.checkSum(iArr);
    }

    public static void vMeth(byte by, int i2, int i3) {

        int i4=-205, i5=4;
        float f1=2.833F, f2=1.92F;

        for (i4 = 284; i4 > 14; --i4) {
            vMeth1(i3);
            f1 = 6;
            do {
                float f3=-22.882F;
                Test.iArrFld[i4 + 1] = i5;
                switch (((i4 % 6) * 5) + 108) {
                case 111:
                    switch ((((i3 >>> 1) % 6) * 5) + 127) {
                    case 132:
                        Test.iArrFld[i4 + 1] *= i4;
                        i3 = (int)Test.instanceCount;
                        break;
                    case 131:
                        i2 = i2;
                        switch ((int)((f1 % 3) + 51)) {
                        case 51:
                            Test.dFld = Test.instanceCount;
                            i3 *= (int)Test.instanceCount;
                            Test.iArrFld[i4] <<= i5;
                            break;
                        case 52:
                            Test.lArrFld[(int)(f1 + 1)] = i5;
                            i2 -= i5;
                            break;
                        case 53:
                            f2 -= i5;
                            break;
                        default:
                            f3 = Test.instanceCount;
                        }
                        break;
                    case 135:
                        i2 = 3;
                        break;
                    case 156:
                    case 157:
                        i2 = i4;
                        break;
                    case 145:
                        Test.instanceCount = (long)Test.dFld;
                        break;
                    }
                    break;
                case 134:
                    i5 = (int)Test.instanceCount;
                    break;
                case 116:
                    if (i5 != 0) {
                        vMeth_check_sum += by + i2 + i3 + i4 + i5 + Float.floatToIntBits(f1) + Float.floatToIntBits(f2);
                        return;
                    }
                    break;
                case 133:
                case 129:
                    Test.iArrFld[(int)(f1)] -= (int)Test.instanceCount;
                    break;
                case 138:
                    i5 = (int)Test.instanceCount;
                    break;
                default:
                    Test.iArrFld[i4] *= i4;
                }
            } while (--f1 > 0);
        }
        vMeth_check_sum += by + i2 + i3 + i4 + i5 + Float.floatToIntBits(f1) + Float.floatToIntBits(f2);
    }

    public static int iMeth(long l, long l1) {

        byte by1=62;
        int i7=-18, i8=12, i9=-89, i10=-12, i11=-9, i12=32737, i13=13, i14=-9, i15=4, i16=-114;
        short s=9231;

        vMeth(by1, Test.iFld, Test.iFld);
        for (i7 = 6; i7 < 333; ++i7) {
            Test.iFld *= s;
            i8 |= (int)-2467704608L;
            Test.fFld = Test.iFld;
            Test.iArrFld[i7 + 1] = i8;
            Test.fFld += -23;
            Test.fFld *= Test.iFld;
        }
        for (i9 = 7; i9 < 333; i9++) {
            for (i11 = 1; i11 < 5; i11++) {
                for (i13 = 1; i13 < 2; i13++) {
                    l1 -= Test.iFld;
                }
                for (i15 = 1; i15 < 2; i15++) {
                    Test.instanceCount = i13;
                    i12 |= (int)Test.instanceCount;
                }
            }
        }
        long meth_res = l + l1 + by1 + i7 + i8 + s + i9 + i10 + i11 + i12 + i13 + i14 + i15 + i16;
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public void mainTest(String[] strArr1) {

        int i=-9, i1=156, i17=-2464, i18=-34357, i19=-7, i20=11030, i21=-7, i22=8, i23=14958;
        short s1=-8832;
        byte by2=-69;

        for (i = 21; i < 386; i++) {
            iMeth(Test.instanceCount, Test.instanceCount);
            for (i17 = 69; i < i17; i17--) {
                for (i19 = 1; i19 < 1; i19++) {
                    boolean b=true;
                    Test.instanceCount += -40198L;
                    Test.instanceCount += (i19 * i19);
                    Test.instanceCount = i20;
                    i20 = i18;
                    Test.dFld %= (i1 | 1);
                    if (b) {
                        s1 = (short)i18;
                        i20 += i18;
                    } else if (b) {
                        switch (((i % 2) * 5) + 63) {
                        case 67:
                            switch ((i % 7) + 111) {
                            case 111:
                                Test.dFld = i18;
                                i1 += (int)Test.dFld;
                                i18 += i21;
                                break;
                            case 112:
                                by2 += (byte)(((i19 * i18) + Test.fFld) - Test.fFld);
                                by2 = (byte)i21;
                                break;
                            case 113:
                                Test.dFld = Test.fFld;
                                i18 *= i21;
                                break;
                            case 114:
                                switch ((((i20 >>> 1) % 2) * 5) + 123) {
                                case 124:
                                    Test.instanceCount >>= -63878;
                                    break;
                                case 127:
                                    b = false;
                                    break;
                                default:
                                    Test.instanceCount -= i;
                                    switch ((i17 % 5) + 106) {
                                    case 106:
                                        i22 = (int)Test.instanceCount;
                                        Test.instanceCount += (i19 * i19);
                                    case 107:
                                        i21 = i20;
                                    case 108:
                                        i20 += (-102 + (i19 * i19));
                                        break;
                                    case 109:
                                        Test.lArrFld[i17] = i17;
                                        break;
                                    case 110:
                                        Test.instanceCount *= Test.instanceCount;
                                        break;
                                    default:
                                        Test.fFld = -8786;
                                    }
                                }
                                break;
                            case 115:
                                Test.iArrFld[i19] *= i23;
                                break;
                            case 116:
                                Test.iArrFld[(i17 >>> 1) % N] -= i1;
                            case 117:
                                i23 += (int)Test.instanceCount;
                                break;
                            default:
                                Test.instanceCount <<= i17;
                            }
                            break;
                        case 73:
                            i20 += (((i19 * i18) + Test.instanceCount) - i);
                        default:
                            Test.iArrFld[i19 + 1] = -77;
                        }
                    }
                }
            }
        }

        FuzzerUtils.out.println("i i1 i17 = " + i + "," + i1 + "," + i17);
        FuzzerUtils.out.println("i18 i19 i20 = " + i18 + "," + i19 + "," + i20);
        FuzzerUtils.out.println("s1 i21 by2 = " + s1 + "," + i21 + "," + by2);
        FuzzerUtils.out.println("i22 i23 = " + i22 + "," + i23);

        FuzzerUtils.out.println("Test.instanceCount Test.dFld Test.iFld = " + Test.instanceCount + "," +
            Double.doubleToLongBits(Test.dFld) + "," + Test.iFld);
        FuzzerUtils.out.println("Test.fFld Test.iArrFld Test.lArrFld = " + Float.floatToIntBits(Test.fFld) + "," +
            FuzzerUtils.checkSum(Test.iArrFld) + "," + FuzzerUtils.checkSum(Test.lArrFld));

        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
        FuzzerUtils.out.println("iMeth_check_sum: " + iMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test _instance = new Test();
            for (int i = 0; i < 10; i++ ) {
                _instance.mainTest(strArr);
            }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test ->  Test
//DEBUG  main ->  main
//DEBUG  mainTest ->  mainTest
//DEBUG  iMeth ->  iMeth mainTest
//DEBUG  vMeth ->  vMeth iMeth mainTest
//DEBUG  vMeth1 ->  vMeth1 vMeth iMeth mainTest
//DEBUG  Depth = 3
//DEBUG  Classes = 1
//DEBUG  static objects = {}
